---
title: "a 01) Preface to the dayoff package"
author: "Nathan Brouwer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{a) Preface to the dayoff package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warnings = FALSE
)
```

The "dayoff" package is a teaching-oriented *R* package based off of Dr. Avril Coghlan's [*A little book of R for bioinformatics.*](https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/index.html).  Much of the text and code was originally written by Dr. Coghlan and distributed under the [Creative Commons 3.0](https://creativecommons.org/licenses/by/3.0/us/) license.  

## The name of the package

The package is named in honor of pioneering biochemist and bioinformatician [Margaret Dayoff](https://en.wikipedia.org/wiki/Margaret_Oakley_Dayhoff).

## Changes made to original source

To meet the needs of my course I have

1. Edited the original HTML document into  RMarkdown 
1. Used the RStudio IDE instead of the basic R IDE
1. Split up Coghlan's original chapters into short lessons
1. Placed functions written by Coghlan into the R package instead of requiring that they be loaded by hand.  
1. Changed which functions or packages are used; for example, replacing some SeqinR functions with rentrez functions.
1. Added additional plots and changed some plotting functions, such as using ggplot2 and ggpubr.
1. Removed .jpg images; I hope to add these back
1. Fixed typos, removed dead links, and additional links, turned links to hypertext, converted to American English (sorry!)
1. Added a summary section at the beginning listing the functions, vocabulary, software, organism, accession numbers

## New material

A number of new lessons have been added, especially in the "tutorials" folder.  See the vignette "Loading tutorials from the dayoff package" for more information.  Some of these are based off of re-creating figures or tables from the bioinformatics book by Pevsner.  THere are also tutorials related to re-building the original PAM matrices by M. Dayoff.


