devtools::clean_vignettes()
devtools::build_vignettes()
devtools::document(roclets=c('rd', 'collate', 'namespace'))
devtools::load_all(".")
devtools::check()
pkgdown::build_site()

system("git add .")
system("git commit -m update")
system("git push")
